services:
  postgre:
    image: postgres:latest
    restart: always
    container_name: postgre
    ports:
      - 5432:5432
    env_file:
          - .env
    volumes:
      - postgre_dev:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    restart: always
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - redis_dev:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  postgre_dev:
  redis_dev:
